[package]
name = "serde_pickle"
version = "0.1.0"
authors = ["Georg Brandl <georg@python.org>"]
license = "MIT/Apache-2.0"
description = "A serialization library for Python's pickle"
repository = "https://github.com/birkenfeld/serde_pickle"
keywords = ["pickle", "python", "serde", "serialization"]

# For the example binary.
[dev-dependencies]
serde_json = "0.7.0"
rand = "0.3.14"
quickcheck = "0.2.27"

[dependencies]
serde = "0.7.0"
byteorder = "0.4.2"
num-bigint = "0.1.32"
num-traits = "0.1.32"
