[package]
name = "serde-pickle"
version = "0.5.1"
authors = ["Georg Brandl <georg@python.org>"]
license = "MIT/Apache-2.0"
description = "A serde-based serialization library for Python's pickle format"
repository = "https://github.com/birkenfeld/serde-pickle"
documentation = "http://docs.rs/serde-pickle"
keywords = ["pickle", "python", "serde", "serialization"]
edition = "2018"

[dependencies]
serde = "1.0.2"
byteorder = "1.0.0"
num-bigint = "0.2.2"
num-traits = "0.2.2"
iter-read = "0.2.0"

# For the example binary and the test suite.
[dev-dependencies]
serde_derive = "1.0.2"
serde_json = "1.0.0"
rand = "0.7.2"
quickcheck = "0.9.0"
