[package]
name = "serde-pickle"
version = "0.2.0"
authors = ["Georg Brandl <georg@python.org>"]
license = "MIT/Apache-2.0"
description = "A serde-based serialization library for Python's pickle format"
repository = "https://github.com/birkenfeld/serde-pickle"
documentation = "http://birkenfeld.github.io/serde-pickle/serde_pickle/index.html"
keywords = ["pickle", "python", "serde", "serialization"]

[dependencies]
serde = "0.7.0"
byteorder = "0.5.1"
num-bigint = "0.1.32"
num-traits = "0.1.32"

# For the example binary and the test suite.
[dev-dependencies]
serde_macros = "0.7.0"
serde_json = "0.7.0"
rand = "0.3.14"
quickcheck = "0.2.27"
